-- switch_post_view_window_to_10_minutes
-- 생성: 2026-08-04 10:29:34
--
-- 규칙
-- * 이 파일은 머지된 뒤 절대 수정하지 않는다. 변경이 필요하면 새 migration 을 만든다.
-- * 로컬 샘플 데이터는 여기 넣지 않는다. db/seed/seed-local.sql 을 쓴다.
-- * 서로 의존하는 DDL 은 파일을 나누지 말고 이 파일에 함께 담는다.

-- 조회수 중복 방지의 시간 창을 '날짜 칸' 에서 '굴러가는 10분' 으로 바꾼다
-- (docs/community/DOMAIN.md 6.2).
--
-- ▸ 왜 바꾸는가
--
-- 날짜 칸은 같은 사람이 같은 글을 하루에 한 번만 세게 한다. 방어력은 세지만 숫자가
-- 하루 단위로만 움직여서, 글을 다시 열어 본 사람에게는 조회수가 멈춘 값으로 보인다.
-- 10분 창은 반복 조회(새로고침·뒤로가기·댓글 '더 보기') 를 여전히 막으면서 숫자를
-- 살아 있게 한다.
--
-- 상한만 보면 느슨해지는 변경이다 — 뷰어 하나가 하루에 올릴 수 있는 조회수가
-- 1 에서 144 가 된다. 그럼에도 실질 방어력 차이가 크지 않은 것은 비로그인 키가
-- 세션 id 라서 **작정한 조작에는 두 창 모두 무력하기 때문이다**(6.2, PLAN.md R12).
-- 두 설계가 실제로 막는 것은 사람의 반복 조회이고, 그건 10분으로도 막힌다.
--
-- ▸ 왜 UNIQUE 를 버리는가
--
-- 굴러가는 창은 UNIQUE 로 표현할 수 없다. 그런데 애초에 중복을 실제로 막고 있던 것은
-- 이 제약이 아니라 increaseViewCount 가 posts 행에 먼저 거는 배타 잠금이다 — 같은 글의
-- 조회 요청들은 그 UPDATE 에서 줄을 서고, 잠금을 쥔 뒤에 NOT EXISTS 를 보므로 앞 요청이
-- 남긴 이력을 반드시 본다. 제약은 그 잠금 순서가 깨졌을 때 울리는 경보였다.
--
-- 경보를 잃는 것은 실제 손실이며, 대신 CommunityViewCountConcurrencyTests 가 그 자리를
-- 맡는다(H14). 잠금 순서를 되돌리면 교착이 나므로 동시성 테스트가 더 직접적으로 잡는다.
--
-- ▸ 왜 viewed_at 컬럼을 새로 만들지 않는가
--
-- created_at 이 이미 그 값이다. post_views 는 append-only 조회 이력이라 '행이 생긴 시각'
-- 과 '조회한 시각' 이 같다. 같은 값을 담는 컬럼을 하나 더 두면 언젠가 둘이 어긋난다.
-- DB 의 CURRENT_TIMESTAMP(6) 로 잡히는 것도 그대로다 — 서버가 여러 대여도 시계는 하나다.

-- ▸ 왜 viewed_on 을 여기서 지우지 않는가 (expand-contract)
--
-- 이 migration 은 **확장(expand) 단계만** 한다. viewed_on 은 지우지 않고 NULL 허용으로
-- 만 바꾸며, 컬럼 삭제(contract) 는 구버전이 모두 내려간 뒤 별도 migration 이 한다.
--
-- 한 파일에서 다 하면 배포 순서가 어느 쪽이든 상세 요청이 500 이 된다. migration 을
-- 먼저 적용하면 구버전 CommunityMapper 의 viewed_on 조회·INSERT 가 Unknown column 으로
-- 죽고, 새 애플리케이션을 먼저 올리면 아직 NOT NULL 인 viewed_on 을 생략한 recordView
-- 가 죽는다. NULL 허용으로 두면 **양쪽 코드가 같은 스키마에서 함께 동작한다** — 구버전은
-- 날짜를 넣고, 신버전은 넣지 않는다.
--
-- 되돌리는 경우: 신버전이 남긴 행은 viewed_on 이 NULL 이라 구버전의 날짜 창 판단
-- (viewed_on = CURRENT_DATE) 에 걸리지 않는다. 그 구간의 재조회는 다시 세어진다. 되돌린
-- 뒤 잠깐 조회수가 더 오르는 것뿐이라 손해가 없는 쪽으로 틀린다.
--
-- ▸ 세 작업의 순서가 규칙이고, 그래서 한 문장이다
--
-- (1) 새 인덱스를 **먼저** 만든다. fk_post_views_post 가 post_id 로 시작하는 인덱스를
--     요구하는데, 지금 그것을 제공하는 유일한 인덱스가 지우려는 UNIQUE 다. 순서를
--     뒤집으면 "Cannot drop index: needed in a foreign key constraint" 로 실패한다.
--     새 인덱스도 선두가 post_id 라 그 역할을 그대로 물려받는다.
--
-- (2) UNIQUE 를 **명시적으로** 지운다. 이 작업을 빼고 나중에 viewed_on 만 DROP 하면
--     MariaDB 는 인덱스를 함께 지우는 것이 아니라 그 컬럼만 빼고
--     UNIQUE (post_id, viewer_key) 를 남긴다. 그러면 한 사람이 한 글을 **영원히 한 번만**
--     볼 수 있게 되고, 두 번째 조회부터 recordView 가 예외를 던져 상세가 500 이 된다.
--     조용히 망가지는 쪽이라 (1) 보다 위험하다 — (1) 은 적어도 실패하며 알려 준다.
--
-- (3) viewed_on 을 NULL 허용으로 바꾼다.
--
-- **셋을 한 ALTER TABLE 로 묶는 것이 이 파일의 규칙이다.** MariaDB 의 DDL 은 트랜잭션이
-- 아니라서, 문장을 나누면 Flyway 가 통째로 롤백해 주지 않는다. (1) 이 커밋된 뒤 (2) 가
-- 잠금 시간 초과로 실패하면 DB 에는 새 인덱스만 남고 버전은 기록되지 않아, 재시도가
-- 매번 "Duplicate key name" 으로 죽는다 — 손으로 인덱스를 지우기 전에는 복구되지 않는다.
-- 한 문장이면 부분 적용 자체가 없어 재실행이 언제나 안전하다.
ALTER TABLE `post_views`
    ADD INDEX `ix_post_views_post_viewer_created` (`post_id`, `viewer_key`, `created_at`),
    DROP INDEX `uk_post_views_post_viewer_date`,
    MODIFY COLUMN `viewed_on` DATE NULL COMMENT '날짜 창 시절의 잔재. 신버전은 채우지 않는다. contract 단계에서 삭제한다';

-- view_count 는 손대지 않는다.
--
-- 창이 바뀌어도 지금까지의 이력은 그대로 유효하다 — 행 하나가 조회 한 번이라는 뜻은
-- 변하지 않으므로 view_count == COUNT(post_views) 불변식(H14) 이 계속 성립한다.
-- V20260803_235726 이 0 으로 되돌려야 했던 것과는 상황이 다르다. 그때는 이력 자체가
-- 없어서 재계산할 근거가 없었다.
